[package]
name = "nota"
description = "Record, transcribe and summarise lectures, locally."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nota-engine = { path = "../nota-engine" }

[dev-dependencies]
nota-core = { path = "../nota-core" }
nota-recorder = { path = "../nota-recorder" }

[lints]
workspace = true
