#!/usr/bin/env bash
# Tests check-clippy-bans.sh: on the repo as it is, on the repo with a ban
# taken out, and on small fixtures that each break one rule.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
check=$here/check-clippy-bans.sh
root=$(cd "$here/.." && pwd)
dir=$(mktemp -d)
trap 'rm -rf "$dir"' EXIT

status=0
# expect pass|fail NAME [TEXT...] -- ARGS...: runs the check on ARGS; on a
# failure, each TEXT must be in what it printed.
expect() {
  local want=$1 name=$2 got out
  shift 2
  local texts=()
  while [[ $1 != -- ]]; do
    texts+=("$1")
    shift
  done
  shift
  if out=$("$check" "$@" 2>&1); then got=pass; else got=fail; fi
  if [[ $got != "$want" ]]; then
    echo "check-clippy-bans.sh on $name: expected $want, got $got:" >&2
    echo "$out" >&2
    status=1
    return
  fi
  # The guard keeps bash before 4.4 from calling an empty array unset.
  for t in ${texts[@]+"${texts[@]}"}; do
    if ! grep -qF -- "$t" <<<"$out"; then
      echo "check-clippy-bans.sh on $name: output doesn't name '$t':" >&2
      echo "$out" >&2
      status=1
    fi
  done
}

# The repo as it is.
expect pass repo -- "$root/clippy-crates.txt" "$root/clippy.toml" "$root/Cargo.lock" "$root/fuzz/Cargo.lock"

# The repo with jiff's clock reads taken out of clippy.toml.
grep -vE '"jiff::(Timestamp|Zoned)::now"' "$root/clippy.toml" >"$dir/no-jiff.toml"
expect fail no-jiff 'jiff::Timestamp::now' 'jiff::Zoned::now' -- \
  "$root/clippy-crates.txt" "$dir/no-jiff.toml" "$root/Cargo.lock" "$root/fuzz/Cargo.lock"

# A small tree: the workspace member `nota-app` depends on `clockwork` (which
# reads the clock) and `tidy`; `tidy` depends on `deep`.
cat >"$dir/clippy.toml" <<'EOF'
allow-unwrap-in-tests = true
disallowed-methods = [
  { path = "std::time::Instant::now", reason = "the session clock" },
  { path = "clockwork::Clock::now", reason = "the session clock", allow-invalid = true },
]
disallowed-types = [
  { path = "clockwork::Unlisted", reason = "a type, not a method" },
]
EOF
package() { # NAME [DEP...]: a crates.io package
  local name=$1
  shift
  printf '\n[[package]]\nname = "%s"\nversion = "1.0.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n' "$name"
  if [[ $# -gt 0 ]]; then
    printf 'dependencies = [\n'
    printf ' "%s",\n' "$@"
    printf ']\n'
  fi
}
member() { # NAME DEP...: a package with no source, as workspace members are
  printf '\n[[package]]\nname = "%s"\nversion = "0.0.0"\n' "$1"
  shift
  if [[ $# -gt 0 ]]; then
    printf 'dependencies = [\n'
    printf ' "%s",\n' "$@"
    printf ']\n'
  fi
}
{
  printf '# This file is automatically @generated by Cargo.\nversion = 4\n'
  member nota-app clockwork "tidy 1.0.0"
  package clockwork
  package deep
  package tidy deep
} >"$dir/Cargo.lock"
cat >"$dir/map.txt" <<'EOF'
# A comment.
[ban]
clockwork::Clock::now

[none: pure data]
tidy

[indirect: under tidy]
deep
EOF
base=("$dir/clippy.toml" "$dir/Cargo.lock")
expect pass fixture -- "$dir/map.txt" "${base[@]}"

# A new dependency with a clock read that nobody has classified.
{ cat "$dir/Cargo.lock"; package chrono; } >"$dir/chrono.lock"
expect fail new-dependency 'chrono: not in' -- "$dir/map.txt" "$dir/clippy.toml" "$dir/chrono.lock"

# Classified, but its ban isn't in clippy.toml.
{ cat "$dir/map.txt"; printf '[ban]\nchrono::Utc::now\n'; } >"$dir/chrono-map.txt"
expect fail ban-missing 'chrono::Utc::now is under [ban]' -- "$dir/chrono-map.txt" "$dir/clippy.toml" "$dir/chrono.lock"

# A ban the map lists but clippy.toml lost.
grep -v 'clockwork::Clock::now' "$dir/clippy.toml" >"$dir/lost.toml"
expect fail ban-lost 'clockwork::Clock::now is under [ban]' -- "$dir/map.txt" "$dir/lost.toml" "$dir/Cargo.lock"

# A ban commented out doesn't count, whole or after its path.
sed 's/^  { path = "clockwork::Clock::now"/  # { path = "clockwork::Clock::now"/' "$dir/clippy.toml" >"$dir/commented.toml"
expect fail ban-commented 'clockwork::Clock::now is under [ban]' -- "$dir/map.txt" "$dir/commented.toml" "$dir/Cargo.lock"
sed 's/^  { path = "clockwork::Clock::now"/  { reason = "x" } # path = "clockwork::Clock::now"/' "$dir/clippy.toml" >"$dir/trailing.toml"
expect fail ban-trailing-comment 'clockwork::Clock::now is under [ban]' -- "$dir/map.txt" "$dir/trailing.toml" "$dir/Cargo.lock"
# The repo's own jiff bans, commented out.
sed -E 's/^(  \{ path = "jiff::(Timestamp|Zoned)::now")/#\1/' "$root/clippy.toml" >"$dir/jiff-commented.toml"
expect fail jiff-commented 'jiff::Timestamp::now' 'jiff::Zoned::now' -- \
  "$root/clippy-crates.txt" "$dir/jiff-commented.toml" "$root/Cargo.lock" "$root/fuzz/Cargo.lock"

# A banned type covers its functions: the path under disallowed-types counts,
# and under any other table it doesn't.
{ cat "$dir/map.txt"; printf '[ban]\nclockwork::Unlisted\n'; } >"$dir/type-map.txt"
expect pass ban-as-type -- "$dir/type-map.txt" "${base[@]}"
sed 's/^disallowed-types = \[/other-list = [/' "$dir/clippy.toml" >"$dir/other.toml"
expect fail ban-in-other-table 'clockwork::Unlisted is under [ban]' -- "$dir/type-map.txt" "$dir/other.toml" "$dir/Cargo.lock"

# An [indirect] crate that the workspace now depends on directly.
{ cat "$dir/Cargo.lock"; member nota-other deep; } >"$dir/direct.lock"
expect fail indirect-now-direct 'deep is under [indirect]' -- "$dir/map.txt" "$dir/clippy.toml" "$dir/direct.lock"

# A path dependency outside the workspace has no source either, but it isn't
# one of nota's crates.
{ cat "$dir/Cargo.lock"; member vendored-clock; } >"$dir/path-dep.lock"
expect fail path-dependency 'vendored-clock: not in' -- "$dir/map.txt" "$dir/clippy.toml" "$dir/path-dep.lock"

# A crate the tree no longer has.
printf '[none: gone]\nvanished\n' | cat "$dir/map.txt" - >"$dir/stale.txt"
expect fail stale 'no crate vanished' -- "$dir/stale.txt" "${base[@]}"
printf '[allow: gone]\nvanished::f\n' | cat "$dir/map.txt" - >"$dir/stale-path.txt"
expect fail stale-path 'no crate vanished' -- "$dir/stale-path.txt" "${base[@]}"

# Listed twice, or under [none] with functions listed too.
printf '[none: again]\ntidy\n' | cat "$dir/map.txt" - >"$dir/twice.txt"
expect fail twice 'tidy is already listed' -- "$dir/twice.txt" "${base[@]}"
printf '[allow: it does]\ntidy::write\n' | cat "$dir/map.txt" - >"$dir/contradiction.txt"
expect fail contradiction 'tidy is under [none] but has functions listed' -- "$dir/contradiction.txt" "${base[@]}"

# [allow] takes a whole crate or a path; either needs a reason.
sed 's/^\[none: pure data\]$/[allow: test-only]/' "$dir/map.txt" >"$dir/allow.txt"
expect pass allow-crate -- "$dir/allow.txt" "${base[@]}"
sed 's/^\[none: pure data\]$/[none]/' "$dir/map.txt" >"$dir/no-reason.txt"
expect fail no-reason '[none] needs a reason' -- "$dir/no-reason.txt" "${base[@]}"
sed 's/^\[none: pure data\]$/[none:  ]/' "$dir/map.txt" >"$dir/blank-reason.txt"
expect fail blank-reason '[none] needs a reason' -- "$dir/blank-reason.txt" "${base[@]}"

# Malformed entries.
sed 's/^\[ban\]$/[bans]/' "$dir/map.txt" >"$dir/unknown.txt"
expect fail unknown-section 'unknown section [bans]' -- "$dir/unknown.txt" "${base[@]}"
printf 'stray\n' | cat - "$dir/map.txt" >"$dir/stray.txt"
expect fail before-section 'entry before any section' -- "$dir/stray.txt" "${base[@]}"
sed 's/^tidy$/tidy::write/' "$dir/map.txt" >"$dir/path-in-none.txt"
expect fail path-in-none 'a path under [none]' -- "$dir/path-in-none.txt" "${base[@]}"
printf '[ban]\ntidy\n' | cat "$dir/map.txt" - >"$dir/name-in-ban.txt"
expect fail name-in-ban '[ban] takes paths' -- "$dir/name-in-ban.txt" "${base[@]}"
sed 's/^\[ban\]$/[ban: because]/' "$dir/map.txt" >"$dir/ban-reason.txt"
expect fail ban-reason '[ban] takes no reason' -- "$dir/ban-reason.txt" "${base[@]}"
sed 's/^\[none: pure data\]$/[none: pure data/' "$dir/map.txt" >"$dir/header.txt"
expect fail bad-header 'not a section header' -- "$dir/header.txt" "${base[@]}"
printf '[ban]\nclockwork::Clock-now\n' | cat "$dir/map.txt" - >"$dir/bad-path.txt"
expect fail bad-path 'not a path: clockwork::Clock-now' -- "$dir/bad-path.txt" "${base[@]}"
printf '[allow: again]\nclockwork::Clock::now\n' | cat "$dir/map.txt" - >"$dir/path-twice.txt"
expect fail path-twice 'clockwork::Clock::now is already listed' -- "$dir/path-twice.txt" "${base[@]}"
sed 's/^tidy$/tidy!/' "$dir/map.txt" >"$dir/bad-name.txt"
expect fail bad-name 'not a crate name: tidy!' -- "$dir/bad-name.txt" "${base[@]}"

# Arguments.
expect fail missing-file "can't read" -- "$dir/map.txt" "$dir/clippy.toml" "$dir/none.lock"
if "$check" "$dir/map.txt" "$dir/clippy.toml" >/dev/null 2>&1; then
  echo "check-clippy-bans.sh with no lock file: expected a usage error" >&2
  status=1
fi

exit "$status"
